# This is meant to be run on a schedule, and will just pull common search terms and dump them in S3
fetch:
  stage: build
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - docker build -t example/hello-world .
    - docker tag example/hello-world $ACCOUNT_NUMBER.dkr.ecr.$REGION.amazonaws.com/testing-ecr-repo:latest
    - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_NUMBER.dkr.ecr.$REGION.amazonaws.com
    - docker push $ACCOUNT_NUMBER.dkr.ecr.$REGION.amazonaws.com/testing-ecr-repo:latest
    - docker push $ACCOUNT_NUMBER.dkr.ecr.$REGION.amazonaws.com/testing-ecr-repo:${VERSION_NUMBER}


fetchy:
  stage: deploy
  image: hashicorp/terraform:latest
  script:
    - terraform apply -var="image_full=$ACCOUNT_NUMBER.dkr.ecr.$REGION.amazonaws.com/testing-ecr-repo:${VERSION_NUMBER}" -auto-approve
